# Generated by Django 4.1.7 on 2023-05-27 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.CharField(max_length=10)),
                ("issue_date", models.DateField()),
                ("valid_until", models.DateField()),
                ("surname", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=50)),
                ("patronymic", models.CharField(max_length=50)),
                ("form_of_study", models.CharField(max_length=50)),
                ("faculty", models.CharField(max_length=100)),
                ("structural_unit", models.CharField(max_length=100)),
                ("group_number", models.CharField(max_length=10)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
